// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaflhhmjgpzcgplpldjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZmxoaG1qZ3B6Y2dwbHBsZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTc1MjYsImV4cCI6MjA2OTM5MzUyNn0.FzAZfs9SUFp8nb3Bss33VSqIKv5OZTQ3bkToO4sVN0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});